### ISSUE TITLE
More WMS?

### ISSUE THREAD

**Issue by ajpelu** [dieghernan/leaflet-providersESP#4]
Hi @dieghernan
Thanks for this plugin. 
I've used this extension to add base maps directly in leaflet, but also I would like to use as base maps in R, using the amazing mapSpain pkg. I read the documentation and I see how to do it, but I didn't find any way to include custom WMS, for instance from other institutions (e.g. from Junta de Andalucía). 

Any suggestions?

Thanks and sorry for this mixed questions.

**Comment by dieghernan** [comment]
HI @ajpelu:

For interactive (i.e. Leaflet maps) the solution is quite straightforward, while for static maps in R it is more complex. 

In first place, let me tell you that I am planning a new release of [**mapSpain**](https://github.com/rOpenSpain/mapSpain/) on the next weeks, so if you want to add new providers you may **consider a pull request** to [the plugin in dev](https://github.com/dieghernan/leaflet-providersESP/blob/master/dev/leaflet-providersESP.js) and I would happily add those providers both to this plugin and to **mapSpain**:

In the meantime, you can do the following:

## Leaflet maps (Leaflet.js and R)

You really don't need mapSpain for this, let me show you how (although you may already know this).

Lets say we want to add https://www.ideandalucia.es/wms/ortofoto2016?request=GetCapabilities&service=WMS ("ortofotografia_2016_pancromatico") layer (search for `queryable=` to see the `<Name>` of the layers). 

On **Leaflet.js** use `L.tileLayer.wms()`:
<details>
    <summary>Leaflet.js</summary>

```html

<!DOCTYPE html>
<html>
<head>
	<title>Minimal page | leaflet-providersESP</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Load Leaflet -->
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
	<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
	<!-- Install leaflet-providersESP -->
	<!-- Display map full page -->
	<style>
	html {height: 100%}
	body {height: 100%;margin: 0;padding: 0;}
	#map {height: 100%;width: 100%}
	</style>
</head>
<body>
<!-- Create map -->
	<div id="map"></div>
        <script>
            var map = L.map("map", {
                center: [37.17634,  -3.58821],
                zoomControl: true,
                zoom: 7,
            });
            
			osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
				attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
			}).addTo(map);
			
            // Junta Andalucia			
            and = L.tileLayer.wms("https://www.ideandalucia.es/wms/ortofoto2016?",{
				  layers: "ortofotografia_2016_pancromatico",
				  format: "image/png",
				  transparent: true,
				  attribution: "IDEAndalucia"
				}).addTo(map);
           
           var baseLayers = {"OpenStreetMap": osm};
		   var overlays = {"Junta Andalucia": and};
		   L.control.layers(baseLayers, overlays, {collapsed:false}).addTo(map);
           </script>
</body>
```
</details>

In **R** use the **leaflet**  package:

```r
library(leaflet)

leaflet() %>%
  setView(
    lat = 37.17634,
    lng = -3.58821,
    zoom = 7
  ) %>%
  addProviderTiles("OpenStreetMap", group = "OpenStreetMap") %>%
  addWMSTiles("https://www.ideandalucia.es/wms/ortofoto2016?",
    layers = "ortofotografia_2016_pancromatico",
    options = WMSTileOptions(
      format = "image/png",
      transparent = TRUE,
      attribution = "IDEAndalucia"
    ),
    group = "Junta Andalucia"
  ) %>%
  addLayersControl(
    baseGroups = "OpenStreetMap",
    overlayGroups = "Junta Andalucia",
    options = layersControlOptions(collapsed = FALSE)
  )
```
![image](https://user-images.githubusercontent.com/25656809/202655379-4249b1ee-b893-44fc-9b0c-bbbbcc69e52f.png)

## With mapSpain (static tiles)

Continues on https://github.com/rOpenSpain/mapSpain/issues/86

**Comment by ajpelu** [comment]
Thanks @dieghernan for your detailed reply. 
Yes, I know how to add wms in leaflet and in R, but thanks for the examples. 

About the next release of mapSpain, I'll try to add some new providers. 

Thanks 
AntonioJ

**Comment by dieghernan** [comment]
Hi @ajpelu , just wanted to check if you saw https://github.com/rOpenSpain/mapSpain/issues/86

Regards

**Comment by ajpelu** [comment]
Hi @dieghernan Thanks a lot. This is just what I was looking for.
